### ISSUE TITLE
-Werror=empty-stmt flags errors but doesn't display them

### ISSUE THREAD

**Issue by jrudess** [MikePopoloski/slang#810] opened 2023-08-17 22:14 UTC
I have an environment where there are no empty-stmt warnings being flagged and the run passes with 152 warnings.  But when I rerun with ```-Werror=empty-stmt``` then the run fails but doesn't print any errors:

```
Build failed: 324 errors, 152 warnings
```

Do you have any recommendations on how to track this down?  The compile does have many unused modules, but a simple test-case with unused modules does print the errors, and I haven't found a reproducer yet.

**Comment by jrudess** [comment] 2023-08-17 22:26
Ah, of course.  This is happening because of --suppress-warnings.  The warnings exist in files that are in the suppression list.   When the warning is converted to an error, it looks like the warning still gets suppressed.

**Comment by MikePopoloski** [comment] 2023-08-17 23:08
That's not the intended behavior. I'll fix it.

**Comment by MikePopoloski** [comment] 2023-08-17 23:37
Fixed in 4b9e3f1845dfdb50255aefcd731897d7ff1fc4c4

**Closed by MikePopoloski** 2023-08-17 23:37 UTC
