### ISSUE TITLE
I don't understand something about the notes of InstanceSymbol::resolvePortConnections

### ISSUE THREAD

**Issue by luckyhorse1** [MikePopoloski/slang#375] opened 2020-12-25 13:24 UTC
## the notes of InstanceSymbol::resolvePortConnections
```c++
// Note: the order of operations here is very subtly important.
// In order to resolve connections, we need to actually know our list of ports.
// Asking the body for the list of ports requires fully elaborating the instance,
// especially because of things like non-ansi port declarations which might be
// deep in the body. That process of elaboration can actually depend back on the
// port connections because of interface ports.
// For example:
 //     interface I #(parameter int i) (); endinterface
  //     module M(I iface, input logic [iface.i - 1 : 0] foo);
  //         localparam int j = $bits(foo);
  //     endmodule
  //
  // In order to resolve connections for an instance of M, we elaborate its body,
  // which then requires evaluating $bits(foo) which then depends on the connection
  // provided to `iface`.
```
- why  resolve connections need to elaborate its body?
- for ansi-port，just like above，there is no need to elaborate body when resolve connections.
- for non-ansi-port, there is no interface port. so, this does not exist
- so ,i dont think it's very subtly important.

**Comment by MikePopoloski** [comment] 2020-12-25 20:08
This issue is a duplicate of a question in the Discussions section.

**Closed by MikePopoloski** 2020-12-25 20:08 UTC
